/**
 * Effect-native client projected directly from the canonical NativeApi contract.
 *
 * @since 0.2.0
 */
import { ExternalNativeApi } from "@vektorprogrammet/http-api";
import { Predicate, Effect } from "effect";
import { FetchHttpClient, HttpClient, HttpClientRequest } from "effect/unstable/http";
import { HttpApiClient } from "effect/unstable/httpapi";
import { apiUrl } from "./config.js";

/** A Cookie header value or a lazy server-side Cookie header reader. */
export type CookieOption = string | (() => string | undefined);

/** Fetch capability supplied by the SDK composition root. */
export type FetchCapability = Effect.Success<typeof FetchHttpClient.Fetch>;

/** Runtime options shared by every generated operation. */
export interface ClientOptions {
  readonly cookie?: CookieOption;
  readonly fetch?: FetchCapability;
  readonly origin?: string;
  readonly headers?: Readonly<Record<string, string>> | (() => Readonly<Record<string, string>>);
}

const resolveCookie = (cookie: CookieOption | undefined): string | undefined =>
  Predicate.isFunction(cookie) ? cookie() : cookie;

const resolveHeaders = (headers: ClientOptions["headers"]): Readonly<Record<string, string>> =>
  Predicate.isFunction(headers) ? headers() : (headers ?? {});

const transformClient =
  (options: ClientOptions) =>
  (client: HttpClient.HttpClient): HttpClient.HttpClient =>
    client.pipe(
      HttpClient.mapRequest((request) => {
        let next = HttpClientRequest.setHeaders(request, resolveHeaders(options.headers));
        const cookie = resolveCookie(options.cookie);

        if (cookie !== undefined && cookie.length > 0)
          next = HttpClientRequest.setHeader(next, "Cookie", cookie);

        if (options.origin !== undefined && options.origin.length > 0)
          next = HttpClientRequest.setHeader(next, "Origin", options.origin);

        return next;
      }),
      HttpClient.transformResponse((response) => {
        const operation = response.pipe(
          Effect.provideService(FetchHttpClient.RequestInit, { credentials: "include" }),
        );

        return options.fetch === undefined
          ? operation
          : operation.pipe(Effect.provideService(FetchHttpClient.Fetch, options.fetch));
      }),
    );

const makeNativeClient = (
  baseUrl: string | undefined,
  options: ClientOptions,
): Effect.Effect<NativeClient> =>
  HttpApiClient.make(ExternalNativeApi, {
    baseUrl,
    transformClient: transformClient(options),
  }).pipe(Effect.provide(FetchHttpClient.layer));

type NativeClient = HttpApiClient.Client<
  (typeof ExternalNativeApi.groups)[keyof typeof ExternalNativeApi.groups]
>;

/**
 * Creates the complete Effect SDK directly from `ExternalNativeApi`.
 *
 * The Effect HTTP API client owns request encoding, response decoding, and the
 * endpoint error channel. No SDK-local route registry or response decoder is
 * involved.
 */
export const createEffectClient = (
  baseUrl: string | undefined,
  options: ClientOptions = {},
): NativeClient => Effect.runSync(makeNativeClient(baseUrl, options));

/** Creates an Effect SDK from the SDK-owned environment configuration. */
export const createConfiguredEffectClient = (options: ClientOptions = {}): NativeClient =>
  createEffectClient(apiUrl, options);

/** Public Effect SDK shape generated by Effect from `ExternalNativeApi`. */
export type EffectSdk = NativeClient;
