/**
 * Effect-native client projected directly from the canonical NativeApi contract.
 *
 * @since 0.2.0
 */
import { ExternalNativeApi } from "@vektorprogrammet/http-api";
import { Effect } from "effect";
import { FetchHttpClient, HttpClient, HttpClientRequest } from "effect/unstable/http";
import { HttpApiClient } from "effect/unstable/httpapi";
import { apiUrl } from "./config.js";

/** A Cookie header value or a lazy server-side Cookie header reader. */
export type CookieOption = string | (() => string | undefined);

/** Fetch capability supplied by the SDK composition root. */
export type FetchCapability = typeof globalThis.fetch;

/** Runtime options shared by every generated operation. */
export interface ClientOptions {
  readonly cookie?: CookieOption;
  readonly fetch?: FetchCapability;
  readonly origin?: string;
  readonly headers?: Readonly<Record<string, string>> | (() => Readonly<Record<string, string>>);
}

const resolveCookie = (cookie: CookieOption | undefined): string | undefined =>
  typeof cookie === "function" ? cookie() : cookie;

const resolveHeaders = (headers: ClientOptions["headers"]): Readonly<Record<string, string>> =>
  typeof headers === "function" ? headers() : (headers ?? {});

const transformClient = (
  options: ClientOptions,
): ((client: HttpClient.HttpClient) => HttpClient.HttpClient) =>
  HttpClient.mapRequest((request) => {
    let next = HttpClientRequest.setHeaders(request, resolveHeaders(options.headers));
    const cookie = resolveCookie(options.cookie);
    if (cookie !== undefined && cookie.length > 0) {
      next = HttpClientRequest.setHeader(next, "Cookie", cookie);
    }
    if (options.origin !== undefined && options.origin.length > 0) {
      next = HttpClientRequest.setHeader(next, "Origin", options.origin);
    }
    return next;
  });

const makeNativeClient = (baseUrl: string | undefined, options: ClientOptions) =>
  HttpApiClient.make(ExternalNativeApi, {
    ...(baseUrl === undefined ? {} : { baseUrl }),
    transformClient: transformClient(options),
  }).pipe(Effect.provide(FetchHttpClient.layer));

type NativeClient = Effect.Success<ReturnType<typeof makeNativeClient>>;

type AnyEffectMethod = (...args: ReadonlyArray<never>) => Effect.Effect<unknown, unknown, unknown>;

const bindRuntime = <A>(value: A, options: ClientOptions): A => {
  if (typeof value === "function") {
    const method = value as AnyEffectMethod;
    return ((...args: ReadonlyArray<never>) => {
      let operation = method(...args);
      if (options.fetch !== undefined) {
        operation = operation.pipe(Effect.provideService(FetchHttpClient.Fetch, options.fetch));
      }
      operation = operation.pipe(
        Effect.provideService(FetchHttpClient.RequestInit, { credentials: "include" }),
      );
      return operation;
    }) as A;
  }
  if (typeof value !== "object" || value === null) return value;

  const output: Record<string, unknown> = {};
  for (const [key, child] of Object.entries(value)) {
    output[key] = bindRuntime(child, options);
  }
  return output as A;
};

/**
 * Creates the complete Effect SDK directly from `ExternalNativeApi`.
 *
 * The Effect HTTP API client owns request encoding, response decoding, and the
 * endpoint error channel. No SDK-local route registry or response decoder is
 * involved.
 */
export const createEffectClient = (
  baseUrl: string | undefined,
  options: ClientOptions = {},
): NativeClient => bindRuntime(Effect.runSync(makeNativeClient(baseUrl, options)), options);

/** Creates an Effect SDK from the SDK-owned environment configuration. */
export const createConfiguredEffectClient = (options: ClientOptions = {}): NativeClient =>
  createEffectClient(apiUrl, options);

/** Public Effect SDK shape generated by Effect from `ExternalNativeApi`. */
export type EffectSdk = NativeClient;
