// Re-export the Promise surface as the default API
export { createClient, type Sdk, type ClientOptions } from "./promise.js";
export { apiUrl, isFixtureMode } from "./config.js";

// Error types for instanceof checks
export {
  SdkError,
  UnauthorizedError,
  NotFoundError,
  ValidationError,
  ConflictError,
  NetworkError,
  RateLimitedError,
  ConfigurationError,
  ReceiptRejectionError,
  UnauthenticatedActorError,
  InactiveActorError,
  ReceiptOwnerDeniedError,
  ReceiptScopeDeniedError,
  ReceiptDecodeSdkError,
  ReceiptAlreadyExistsError,
  DuplicateReceiptCommandConflictError,
  ReceiptNotFoundError,
  StaleReceiptRevisionError,
  InvalidReceiptTransitionError,
  ReceiptFileNotStagedError,
  ReceiptPersistenceSdkError,
} from "./errors.js";
export type { SdkErrorType, ReceiptRejectionTag, OrganizationRejectionTag } from "./errors.js";
export {
  OrganizationRejectionError,
  OrganizationUnauthenticatedActorError,
  OrganizationRoleDeniedError,
  OrganizationInvalidReferenceError,
  OrganizationCommandConflictError,
  OrganizationDecodeSdkError,
  OrganizationRequestBodyTooLargeError,
  OrganizationPersistenceSdkError,
} from "./errors.js";

export type { Receipt, AdminReceipt, ReceiptInput } from "./schemas/receipt.js";
export {
  CommandId,
  CommandIdSchema,
  ReceiptCommandObservation,
  ReceiptCommandObservationSchema,
  ReceiptFile,
  ReceiptFileSchema,
  ReceiptId,
  ReceiptIdSchema,
  ReceiptOwnerFilter,
  ReceiptApprovalFilter,
  ReceiptApprovalFilterSchema,
  ReceiptOwnerFilterSchema,
  ReceiptPage,
  ReceiptPageSchema,
  ReceiptProjection,
  ReceiptProjectionSchema,
  ReceiptResolutionInput,
  ReceiptResolutionInputSchema,
  ReceiptReviseInput,
  ReceiptReviseInputSchema,
  ReceiptRevision,
  ReceiptRevisionSchema,
  ReceiptStatus,
  ReceiptStatusSchema,
  ReceiptSubmitInput,
  ReceiptSubmitInputSchema,
  ReceiptWithdrawInput,
  ReceiptWithdrawInputSchema,
} from "./schemas/receipt.js";
export type { Application, ApplicationDetail } from "./schemas/application.js";
export {
  AdminInterviewList,
  Interview,
  InterviewId,
  InterviewScheduleInput,
  InterviewSchedulingStatus,
} from "./schemas/interview.js";
export { ContactMessageInput, ContactMessageInputSchema } from "./schemas/contact-message.js";
export type { User, UserProfile } from "./schemas/user.js";
export type { DashboardStats } from "./schemas/dashboard.js";
export type { TeamInterest, Sponsor, MailingList, AdmissionStats, Page } from "./schemas/common.js";
export {
  DepartmentId,
  TeamId,
  FieldOfStudyId,
  OrganizationCommandId,
  OrganizationEntityKindSchema,
  DepartmentJsonSchema,
  TeamJsonSchema,
  FieldOfStudyJsonSchema,
  DepartmentListSchema,
  TeamListSchema,
  FieldOfStudyListSchema,
  CreateDepartmentCommandSchema,
  CreateTeamCommandSchema,
  CreateFieldOfStudyCommandSchema,
  OrganizationCreateCommandSchema,
  DepartmentCreatedObservationSchema,
  TeamCreatedObservationSchema,
  FieldOfStudyCreatedObservationSchema,
  OrganizationCreatedObservationSchema,
  DepartmentReplayedObservationSchema,
  TeamReplayedObservationSchema,
  FieldOfStudyReplayedObservationSchema,
  OrganizationReplayedObservationSchema,
  OrganizationCreateObservationSchema,
  CreateDepartmentResultSchema,
  CreateTeamResultSchema,
  CreateFieldOfStudyResultSchema,
  OrganizationCreateResultSchema,
} from "./schemas/organization.js";
export type {
  OrganizationEntityKind,
  DepartmentJson,
  TeamJson,
  FieldOfStudyJson,
  DepartmentList,
  TeamList,
  FieldOfStudyList,
  CreateDepartmentCommand,
  CreateTeamCommand,
  CreateFieldOfStudyCommand,
  OrganizationCreateCommand,
  DepartmentCreatedObservation,
  TeamCreatedObservation,
  FieldOfStudyCreatedObservation,
  OrganizationCreatedObservation,
  DepartmentReplayedObservation,
  TeamReplayedObservation,
  FieldOfStudyReplayedObservation,
  OrganizationReplayedObservation,
  OrganizationCreateObservation,
  CreateDepartmentResult,
  CreateTeamResult,
  CreateFieldOfStudyResult,
  OrganizationCreateResult,
} from "./schemas/organization.js";
export type { SchedulingAssistant, SchedulingSchool, Substitute } from "./schemas/scheduling.js";
export type { ClientContext } from "./context.js";

export {
  AdmissionPeriodRejectionError,
  AdmissionRoleDeniedError,
  AdmissionScopeDeniedError,
  DepartmentRequiredError,
  DepartmentNotFoundError,
  SemesterNotFoundError,
  AdmissionPeriodNotFoundError,
  AdmissionPeriodDecodeSdkError,
  InvalidAdmissionPeriodWindowError,
  AdmissionWindowOutsideSemesterError,
  AdmissionPeriodAlreadyExistsError,
  StaleAdmissionPeriodRevisionError,
  DuplicateAdmissionPeriodCommandConflictError,
  AdmissionPeriodPersistenceSdkError,
  PublicApplicationRejectionError,
  PublicApplicationDecodeSdkError,
  NoEligibleAdmissionPeriodError,
  PublicApplicationDepartmentNotFoundError,
  PublicApplicationFieldOfStudyNotFoundError,
  PublicApplicationFieldOfStudyInactiveError,
  PublicApplicationFieldOfStudyDepartmentMismatchError,
  DuplicatePublicApplicationError,
  DuplicatePublicApplicationCommandConflictError,
  RequestBodyTooLargeError,
  PublicApplicationRateLimitExceededError,
  PublicApplicationNotFoundError,
  PublicApplicationPersistenceSdkError,
} from "./promise.js";
export type {
  AdmissionPeriodRejectionTag,
  PublicApplicationRejectionTag,
  AdmissionPeriodCommandObservation,
  AdmissionPeriodList,
} from "./promise.js";
export {
  PublicApplicationSubmitInput,
  PublicApplicationSubmitInputSchema,
  PublicApplicationSubmitResponse,
  PublicApplicationSubmitResponseSchema,
  PublicApplicationFieldOfStudy,
  PublicApplicationFieldOfStudySchema,
  PublicApplicationDepartment,
  PublicApplicationDepartmentSchema,
  PublicApplicationCatalog,
  PublicApplicationCatalogSchema,
  PublicApplicationConfirmation,
  PublicApplicationConfirmationSchema,
} from "./promise.js";
export {
  AdmissionPeriod,
  AdmissionPeriodProjection,
  AdmissionPeriodCreateInput,
  AdmissionPeriodReviseInput,
  AdmissionPeriodPage,
} from "./promise.js";
export {
  RecruitmentRejectionError,
  RecruitmentUnauthenticatedActorError,
  RecruitmentInactiveActorError,
  RecruitmentRoleDeniedError,
  RecruitmentScopeDeniedError,
  RecruitmentAdmissionPeriodNotFoundError,
  RecruitmentAmbiguousAdmissionPeriodError,
  RecruitmentApplicationNotFoundError,
  RecruitmentApplicationAlreadyAssignedError,
  RecruitmentInterviewSchemaNotFoundError,
  RecruitmentInterviewSchemaInactiveError,
  RecruitmentInterviewerNotEligibleError,
  RecruitmentAssignmentCommandConflictError,
  RecruitmentDecodeSdkError,
  RecruitmentPersistenceSdkError,
  RecruitmentInterviewNotFoundError,
  RecruitmentInvitationNotFoundError,
  RecruitmentInvitationAlreadyRespondedError,
  RecruitmentInterviewAlreadyScheduledError,
  RecruitmentInterviewStaleRevisionError,
  RecruitmentScheduleCommandConflictError,
  RecruitmentScheduleInPastError,
  RecruitmentProfileContactNotFoundError,
  InterviewSchemaId,
  RecruitmentAdmissionPeriodId,
  RecruitmentInterviewId,
  RecruitmentAssignmentCommandId,
  RecruitmentScheduleCommandId,
  RecruitmentInvitationId,
  RecruitmentNotificationEffectId,
  RecruitmentInvitationCapabilitySchema,
  RecruitmentApplicationId,
  RecruitmentApplicantId,
  RecruitmentPersonId,
  RecruitmentDepartmentId,
  RecruitmentAssignmentStatusSchema,
  RecruitmentAssignmentBoardQuerySchema,
  RecruitmentAssignmentBoardSchema,
  RecruitmentAssignmentCandidateSchema,
  RecruitmentAssignmentCommandSchema,
  RecruitmentAssignmentObservationSchema,
  RecruitmentAssignmentResultSchema,
  RecruitmentInterviewSchema,
  RecruitmentInterviewerOptionSchema,
  RecruitmentInterviewSchemaOptionSchema,
  RecruitmentInvitationResponseStateSchema,
  RecruitmentInvitationResponseMessageSchema,
  RecruitmentInvitationRejectInputSchema,
  RecruitmentInvitationRequestNewTimeInputSchema,
  RecruitmentInvitationResponseObservationSchema,
  RecruitmentNotificationDeliveryStateSchema,
  RecruitmentInterviewScheduleSchema,
  RecruitmentSchedulingApplicantSchema,
  RecruitmentSchedulingInterviewerSchema,
  RecruitmentSchedulingInterviewSchema,
  RecruitmentSchedulingBoardSchema,
  RecruitmentScheduleCommandSchema,
  RecruitmentScheduleObservationSchema,
  RecruitmentScheduleResultSchema,
} from "./promise.js";
export type {
  RecruitmentRejectionTag,
  RecruitmentInvitationCapability,
  RecruitmentInvitationResponseMessage,
  RecruitmentInvitationResponseObservation,
  RecruitmentInvitationRejectInput,
  RecruitmentInvitationRequestNewTimeInput,
  RecruitmentAssignmentStatus,
  RecruitmentAssignmentBoardQuery,
  RecruitmentAssignmentBoard,
  RecruitmentAssignmentCandidate,
  RecruitmentAssignmentCommand,
  RecruitmentAssignmentObservation,
  RecruitmentAssignmentResult,
  RecruitmentInterview,
  RecruitmentInterviewerOption,
  RecruitmentInterviewSchemaOption,
  RecruitmentInvitationResponseState,
  RecruitmentNotificationDeliveryState,
  RecruitmentInterviewSchedule,
  RecruitmentSchedulingApplicant,
  RecruitmentSchedulingInterviewer,
  RecruitmentSchedulingInterview,
  RecruitmentSchedulingBoard,
  RecruitmentScheduleCommand,
  RecruitmentScheduleObservation,
  RecruitmentScheduleResult,
} from "./promise.js";
