services:
    Tests\Fixtures\RecruitmentAssignmentFixture:
        tags: ['doctrine.fixture.orm']
    Tests\Fixtures\RecruitmentInterviewSchedulingFixture:
        tags: ['doctrine.fixture.orm']
    Tests\Fixtures\RecruitmentInterviewInvitationResponseFixture:
        tags: ['doctrine.fixture.orm']
