[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["apps/server/**"]

[deploy]
preDeployCommand = "/bin/bash /railway-boot.sh"
startCommand = "/bin/bash /railway-start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
