import { createHash } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import frozenContract from "./route-contract.json" with { type: "json" };

export const PREVIEW_APP = "vektor" as const;
export const PREVIEW_STAGE = "p20" as const;
export const PREVIEW_TARGET = "p20" as const;
export const PREVIEW_RESOURCE_PREFIX = "vektor-p20" as const;
export const PREVIEW_CONTAINER = "vektor-p20-container" as const;
export const PREVIEW_HOST = "p20.vektor.phibkro.org" as const;
export const PREVIEW_BASE_URL = `https://${PREVIEW_HOST}` as const;
export const FORBIDDEN_HOST = ["vektorprogrammet", "no"].join(".");

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const SHA = /^sha256:[0-9a-f]{64}$/u;
type App = "homepage" | "dashboard";
export type BasicState = "empty" | "populated" | "loading-safe" | "validation-safe" | "authorization-denied" | "not-found";
export type RouteExpectation = { readonly status: number; readonly basicState: BasicState; readonly redirectTo?: string };
export type PreviewRoute = { readonly id: string; readonly app: App; readonly path: string; readonly sourcePath: string; readonly sourcePattern?: string; readonly kind: "page" | "dynamic-fixture" | "redirect"; readonly expected: RouteExpectation; readonly visual: { readonly desktop: boolean; readonly mobile: boolean } };
export type SourceFile = { readonly path: string; readonly bytes: number; readonly sha256: string };
export type SourceManifest = { readonly files: readonly SourceFile[]; readonly digest: string };
export type RouteContract = { readonly schemaVersion: "preview-route-contract/v1"; readonly generatorVersion: "2026-08-12"; readonly target: { readonly app: "vektor"; readonly stage: "p20"; readonly target: "p20"; readonly host: "p20.vektor.phibkro.org"; readonly resourcePrefix: "vektor-p20"; readonly container: "vektor-p20-container" }; readonly sourceManifestDigest: string; readonly sourceManifests: { readonly homepage: SourceManifest; readonly dashboard: SourceManifest }; readonly routes: readonly PreviewRoute[]; readonly visualEvidence: { readonly desktop: { readonly width: 1440; readonly height: 900 }; readonly mobile: { readonly width: 390; readonly height: 844 } }; readonly namedStates: readonly BasicState[]; readonly contractDigest: string };

function canonical(v: unknown): string { if (v === null || typeof v !== "object") return JSON.stringify(v); if (Array.isArray(v)) return `[${v.map(canonical).join(",")}]`; const o = v as Record<string, unknown>; return `{${Object.keys(o).sort().map((k) => `${JSON.stringify(k)}:${canonical(o[k])}`).join(",")}}`; }
function hash(v: string | Uint8Array): string { return `sha256:${createHash("sha256").update(v).digest("hex")}`; }
function repo(path: string): string { return relative(ROOT, path).split("\\").join("/"); }
function source(paths: readonly string[]): SourceManifest { const files = paths.map((path) => { const bytes = readFileSync(resolve(ROOT, path)); return { path, bytes: bytes.byteLength, sha256: hash(bytes) }; }).sort((a, b) => a.path.localeCompare(b.path)); return { files, digest: hash(canonical(files)) }; }
function routeFiles(path: string): string[] { return readdirSync(path, { withFileTypes: true }).filter((e) => e.isFile() && e.name.endsWith(".tsx")).map((e) => join(path, e.name)).sort(); }
function id(app: App, path: string): string { return `${app}-${path === "/" ? "root" : path.slice(1).replaceAll("/", "-")}`; }
function expectation(app: App, path: string): RouteExpectation { return app === "homepage" ? { status: 200, basicState: "populated" } : path === "/login" || path === "/glemt-passord" || path.startsWith("/tilbakestill-passord/") ? { status: 200, basicState: "validation-safe" } : { status: 302, basicState: "authorization-denied", redirectTo: "/login" }; }
const dynamic: Readonly<Record<string, readonly string[]>> = { "/kontakt/:department": ["aas", "bergen", "hovedstyret", "trondheim"], "/team/:department": ["aas", "bergen", "trondheim"] };
function path(app: App, stem: string): string | null { if (app === "homepage") { if (stem === "_home" || stem === "_home._index") return stem.endsWith("_index") ? "/" : null; if (!stem.startsWith("_home.")) return null; const parts = stem.slice(6).split("."); const isIndex = parts.at(-1) === "_index"; if (isIndex) parts.pop(); if (!isIndex && parts.length === 1 && (parts[0] === "kontakt" || parts[0] === "team")) return null; return `/${parts.map((p) => p.startsWith("$") ? `:${p.slice(1)}` : p).join("/")}`; } if (stem === "_index") return "/"; if (stem === "dashboard") return null; if (stem === "dashboard._index") return "/dashboard"; if (stem === "login") return "/login"; if (stem === "glemt-passord") return "/glemt-passord"; if (stem === "logout") return "/logout"; if (stem === "tilbakestill-passord.$code") return "/tilbakestill-passord/:code"; if (!stem.startsWith("dashboard.")) return null; const parts = stem.slice(10).split("."); if (parts.at(-1) === "_index") parts.pop(); return `/dashboard/${parts.map((p) => p.startsWith("$") ? `:${p.slice(1)}` : p).join("/")}`; }
function build(app: App, files: readonly string[]): PreviewRoute[] { const out: PreviewRoute[] = []; for (const file of files) { const sourcePath = repo(file); const stem = file.slice(file.lastIndexOf("/") + 1).replace(/\.tsx$/u, ""); const pattern = path(app, stem); if (!pattern) continue; const values = pattern.includes(":") ? app === "homepage" ? dynamic[pattern] ?? [] : ["preview-reset-code"] : [pattern]; for (const value of values) { const route = pattern.includes(":") ? pattern.replace(/:[^/]+/u, value) : value; const expected = expectation(app, route); out.push({ id: id(app, route), app, path: route, ...(pattern.includes(":") ? { sourcePattern: pattern } : {}), sourcePath, kind: pattern.includes(":") ? "dynamic-fixture" : expected.status === 302 ? "redirect" : "page", expected, visual: { desktop: true, mobile: true } }); } } return out.sort((a, b) => a.app.localeCompare(b.app) || a.path.localeCompare(b.path)); }
const HOME_INPUTS = ["apps/homepage/src/routes.ts", "apps/homepage/src/nav-routes.ts", "apps/homepage/src/lib/dev-content.ts"] as const;
const DASH_INPUTS = ["apps/dashboard/app/routes.ts", "apps/dashboard/app/lib/auth.server.ts"] as const;
function digestBody(body: Omit<RouteContract, "contractDigest">): string { return hash(canonical(body)); }
export function generateRouteContract(): RouteContract { const homeFiles = routeFiles(join(ROOT, "apps/homepage/src/routes")); const dashFiles = routeFiles(join(ROOT, "apps/dashboard/app/routes")); const homeSource = source([...HOME_INPUTS, ...homeFiles.map(repo)]); const dashSource = source([...DASH_INPUTS, ...dashFiles.map(repo)]); const body: Omit<RouteContract, "contractDigest"> = { schemaVersion: "preview-route-contract/v1", generatorVersion: "2026-08-12", target: { app: PREVIEW_APP, stage: PREVIEW_STAGE, target: PREVIEW_TARGET, host: PREVIEW_HOST, resourcePrefix: PREVIEW_RESOURCE_PREFIX, container: PREVIEW_CONTAINER }, sourceManifestDigest: hash(canonical({ homepage: homeSource, dashboard: dashSource })), sourceManifests: { homepage: homeSource, dashboard: dashSource }, routes: [...build("homepage", homeFiles), ...build("dashboard", dashFiles)], visualEvidence: { desktop: { width: 1440, height: 900 }, mobile: { width: 390, height: 844 } }, namedStates: ["empty", "populated", "loading-safe", "validation-safe", "authorization-denied", "not-found"] }; return { ...body, contractDigest: digestBody(body) }; }
export function assertPreviewBaseUrl(value: string): URL { const url = new URL(value); if (!["http:", "https:"].includes(url.protocol) || url.username || url.password || url.hostname.toLowerCase() === FORBIDDEN_HOST) throw new Error("Unsafe preview base URL"); url.hash = ""; url.search = ""; return url; }
export function assertRouteContractIntegrity(contract: RouteContract): void { if (contract.target.app !== PREVIEW_APP || contract.target.stage !== PREVIEW_STAGE || contract.target.target !== PREVIEW_TARGET || contract.target.resourcePrefix !== PREVIEW_RESOURCE_PREFIX || contract.target.container !== PREVIEW_CONTAINER || contract.target.host === FORBIDDEN_HOST || !SHA.test(contract.sourceManifestDigest)) throw new Error("Invalid route contract identity"); const seen = new Set<string>(); for (const route of contract.routes) { const key = `${route.app}:${route.path}`; if (seen.has(key)) throw new Error(`Duplicate route: ${key}`); seen.add(key); } const body = { schemaVersion: contract.schemaVersion, generatorVersion: contract.generatorVersion, target: contract.target, sourceManifestDigest: contract.sourceManifestDigest, sourceManifests: contract.sourceManifests, routes: contract.routes, visualEvidence: contract.visualEvidence, namedStates: contract.namedStates }; if (digestBody(body) !== contract.contractDigest) throw new Error("Route contract digest mismatch"); }
export function assertFrozenRouteContract(): RouteContract { const frozen = frozenContract as unknown as RouteContract; assertRouteContractIntegrity(frozen); const generated = generateRouteContract(); if (generated.sourceManifestDigest !== frozen.sourceManifestDigest || canonical(generated.routes) !== canonical(frozen.routes)) throw new Error("Route source drift detected"); return frozen; }
export const FROZEN_ROUTE_CONTRACT = frozenContract as unknown as RouteContract;
export function serializeRouteContract(contract: RouteContract): string { return `${JSON.stringify(contract, null, 2)}\n`; }
