<?php

namespace App\Operations\Infrastructure\Repository;

use App\Operations\Infrastructure\Entity\Signature;
use App\Entity\User;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * SignatureRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignatureRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Signature::class);
    }

    /**
     * @return Signature
     */
    public function findByUser(User $user)
    {
        return $this->createQueryBuilder('signature')
            ->select('signature')
            ->where('signature.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
